language: objective-c
osx_image: xcode9
before_install:
- brew update
- brew install carthage || brew outdated carthage || brew upgrade carthage
install:
- carthage bootstrap
branches:
  only:
    - master
    - feature/swift-3
script:
  - set -o pipefail && xcodebuild build test -workspace Haneke.xcworkspace -scheme Haneke-iOS -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.3.1' | xcpretty --color
