language: objective-c
osx_image: xcode7.3
before_install:
- brew update
- brew install carthage || brew outdated carthage || brew upgrade carthage
install:
- carthage bootstrap
branches:
  only:
    - master
script:
  - set -o pipefail && xcodebuild -workspace Haneke.xcworkspace -scheme Haneke-iOS -sdk iphonesimulator9.3 build test | xcpretty --color
